"""scan engine: scan_runs, scan_tasks, resources (autogenerada y revisada manualmente)

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 21:49:37.638670
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('trigger', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_resources', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_deleted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_errors', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_message_safe', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'completed_with_errors', 'failed')", name=op.f('ck_scan_runs_status')),
    sa.CheckConstraint("trigger IN ('manual', 'api', 'cli')", name=op.f('ck_scan_runs_trigger')),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], name=op.f('fk_scan_runs_account_id_cloud_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_runs'))
    )
    op.create_index('ix_scan_runs_account_created', 'scan_runs', ['account_id', 'created_at'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('scope_key', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=64), server_default='', nullable=False),
    sa.Column('service', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('enterprise_project_id', sa.String(length=64), nullable=True),
    sa.Column('provider_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], name=op.f('fk_resources_account_id_cloud_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_run_id'], ['scan_runs.id'], name=op.f('fk_resources_last_run_id_scan_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_resources_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('account_id', 'resource_type', 'scope_key', 'provider_id', name=op.f('uq_resources_account_id_resource_type_scope_key_provider_id'))
    )
    op.create_index('ix_resources_account_region', 'resources', ['account_id', 'region'], unique=False)
    op.create_index('ix_resources_account_service_scope', 'resources', ['account_id', 'service', 'scope_key'], unique=False)
    op.create_index('ix_resources_attributes', 'resources', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_resources_last_run_id'), 'resources', ['last_run_id'], unique=False)
    op.create_index(op.f('ix_resources_project_id'), 'resources', ['project_id'], unique=False)
    op.create_index('ix_resources_tags', 'resources', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('scan_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_run_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('service', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=20), server_default='regional', nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('resource_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deleted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_kind', sa.String(length=32), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('error_message_safe', sa.Text(), nullable=True),
    sa.Column('notices', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("scope IN ('regional', 'global')", name=op.f('ck_scan_tasks_scope')),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'partial', 'failed', 'skipped')", name=op.f('ck_scan_tasks_status')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scan_tasks_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_scan_tasks_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_tasks'))
    )
    op.create_index(op.f('ix_scan_tasks_project_id'), 'scan_tasks', ['project_id'], unique=False)
    op.create_index('ix_scan_tasks_run_sequence', 'scan_tasks', ['scan_run_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scan_tasks_run_sequence', table_name='scan_tasks')
    op.drop_index(op.f('ix_scan_tasks_project_id'), table_name='scan_tasks')
    op.drop_table('scan_tasks')
    op.drop_index('ix_resources_tags', table_name='resources', postgresql_using='gin')
    op.drop_index(op.f('ix_resources_project_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_last_run_id'), table_name='resources')
    op.drop_index('ix_resources_attributes', table_name='resources', postgresql_using='gin')
    op.drop_index('ix_resources_account_service_scope', table_name='resources')
    op.drop_index('ix_resources_account_region', table_name='resources')
    op.drop_table('resources')
    op.drop_index('ix_scan_runs_account_created', table_name='scan_runs')
    op.drop_table('scan_runs')
    # ### end Alembic commands ###
