"""server audit: servidores por cliente (contraseña cifrada) y ejecuciones de server-audit.sh (aditiva)

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-05 15:27:16.854837
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0012'
down_revision: Union[str, None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), server_default='22', nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('host_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('key_version > 0', name=op.f('ck_servers_key_version_positive')),
    sa.CheckConstraint('port BETWEEN 1 AND 65535', name=op.f('ck_servers_port_range')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_servers_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers')),
    sa.UniqueConstraint('client_id', 'name', name=op.f('uq_servers_client_id_name'))
    )
    op.create_index(op.f('ix_servers_client_id'), 'servers', ['client_id'], unique=False)
    op.create_table('server_audit_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('server_name', sa.String(length=100), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('script_sha256', sa.String(length=64), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('hardening_pct', sa.Integer(), nullable=True),
    sa.Column('updates_pct', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('report_html', sa.Text(), nullable=True),
    sa.Column('error_kind', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('requested_by', sa.String(length=200), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed')", name=op.f('ck_server_audit_runs_status')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_server_audit_runs_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_audit_runs_server_id_servers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_audit_runs'))
    )
    op.create_index('ix_server_audit_runs_client_batch', 'server_audit_runs', ['client_id', 'batch_id'], unique=False)
    op.create_index('ix_server_audit_runs_server_created', 'server_audit_runs', ['server_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_server_audit_runs_server_created', table_name='server_audit_runs')
    op.drop_index('ix_server_audit_runs_client_batch', table_name='server_audit_runs')
    op.drop_table('server_audit_runs')
    op.drop_index(op.f('ix_servers_client_id'), table_name='servers')
    op.drop_table('servers')
    # ### end Alembic commands ###
