"""initial multi-client schema (autogenerada y revisada manualmente)

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 21:24:29.506168
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'suspended', 'archived')", name=op.f('ck_clients_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('slug', name=op.f('uq_clients_slug'))
    )
    op.create_table('regions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('endpoint_domain', sa.String(length=255), server_default='myhuaweicloud.com', nullable=False),
    sa.Column('is_supported', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions'))
    )
    op.create_table('service_catalog',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=20), server_default='regional', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope IN ('regional', 'global')", name=op.f('ck_service_catalog_scope')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_catalog'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('cloud_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('huawei_domain_id', sa.String(length=64), nullable=True),
    sa.Column('huawei_domain_name', sa.String(length=200), nullable=True),
    sa.Column('endpoint_domain', sa.String(length=255), server_default='myhuaweicloud.com', nullable=False),
    sa.Column('iam_region_id', sa.String(length=64), nullable=True),
    sa.Column('ak_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('sk_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validation_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'active', 'invalid', 'disabled')", name=op.f('ck_cloud_accounts_status')),
    sa.CheckConstraint('key_version > 0', name=op.f('ck_cloud_accounts_key_version_positive')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_cloud_accounts_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cloud_accounts')),
    sa.UniqueConstraint('client_id', 'name', name=op.f('uq_cloud_accounts_client_id_name'))
    )
    op.create_index(op.f('ix_cloud_accounts_client_id'), 'cloud_accounts', ['client_id'], unique=False)
    op.create_table('user_client_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='viewer', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'operator', 'admin')", name=op.f('ck_user_client_roles_role')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_user_client_roles_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_client_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'client_id', name=op.f('pk_user_client_roles'))
    )
    op.create_index(op.f('ix_user_client_roles_client_id'), 'user_client_roles', ['client_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('huawei_project_id', sa.String(length=64), nullable=False),
    sa.Column('region_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('parent_huawei_project_id', sa.String(length=64), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('huawei_enabled', sa.Boolean(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], name=op.f('fk_projects_account_id_cloud_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_projects_region_id_regions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('account_id', 'huawei_project_id', name=op.f('uq_projects_account_id_huawei_project_id'))
    )
    op.create_index('ix_projects_account_region', 'projects', ['account_id', 'region_id'], unique=False)
    op.create_index(op.f('ix_projects_region_id'), 'projects', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_region_id'), table_name='projects')
    op.drop_index('ix_projects_account_region', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_user_client_roles_client_id'), table_name='user_client_roles')
    op.drop_table('user_client_roles')
    op.drop_index(op.f('ix_cloud_accounts_client_id'), table_name='cloud_accounts')
    op.drop_table('cloud_accounts')
    op.drop_table('users')
    op.drop_table('service_catalog')
    op.drop_table('regions')
    op.drop_table('clients')
    # ### end Alembic commands ###
